# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' inititalizeC
#' 
#' @param n is the sample size
#' 
#' @param cors is the vector of correlations to the initital node.
#'
#' @param alpha is the significance level for the BH test
#'
#' @param conserv (=TRUE or FALSE). If conserv=TRUE, BHY test is used at alpha 
#' otherwise BH test is used at alpha.
#' @details
#' \code{initializeC} takes a vector of correlations, firscher transforms it 
#'  (to get a z-statistic) and computes the pvalues. The BH (or BHY) procedure is 
#'  used on these pvales to reject a set of indices which are then returned
#' @export
initializeC <- function(n, cors, alpha, conserv) {
    .Call('bmdCpp_initializeC', PACKAGE = 'bmdCpp', n, cors, alpha, conserv)
}

#' @title
#' bh_rejectC
#' @description
#' The rcpp version of bhreject 
#' 
#' @param pvals is the vector of pvalues
#'
#' @param alpha is the significance level for the BH test
#' 
#' @param conserv (=TRUE or FALSE). If conserv=TRUE, BHY test is used at level alpha 
#' otherwise BH test is used at level alpha.
#' @details
#' \code{bh_rejectC} takes a vector of p-values and applies the Benjamini Hochberg (Yekutelli)
#' multiple testing procedure at significane level alpha, and returns the indices 
#' of the pvalues which were rejected.
#' @export
bh_rejectC <- function(pvals, alpha, conserv) {
    .Call('bmdCpp_bh_rejectC', PACKAGE = 'bmdCpp', pvals, alpha, conserv)
}

#' @title
#' updateC
#' @description
#' The rcpp version of update5. update5 is first step for a one sided update.
#' One starts with a subset A of X or Y indices, and wishes to get a set B=update5(A)
#' at the other side. Call the otherside as the first side (or the side being tested)
#' and side corresponding to A as the second side.
#' 
#' @param first (either X or Y) is the matrix corresponding to the first side.
#' 
#' @param second (e.g X[,A] or Y[,A]) is the sub-matrix (of the second side)
#' corresponding to the columns of the A.
#' 
#' @param f4ColSums is the rowvector columnSums(first^4)
#' 
#' @param f2 is the matrix first^2
#' 
#' @param f3 is the matrix first^3
#'
#' @param cross is the matrix cor(first, second)
#'
#' @param alpha is the significance level for the BH test
#'
#' @param conserv (=TRUE or FALSE). If conserv=TRUE, BHY test is used at alpha 
#' otherwise BH test is used at alpha.
#' @details
#' \code{updateC} computes the z-statistic corresponding to the sum of 
#' correlations to the second matrix for each column of the first matrix
#' (using the variance formula from SteigerHakstian1982). It converts the 
#' z-statistic to pvalues and rejects the columns of first matrix which 
#' were significant. The indicies corresponding to the significant columns are
#' returned.
#' 
#' @export
updateC <- function(first, second, f4ColSums, f2, f3, cross, alpha, conserv) {
    .Call('bmdCpp_updateC', PACKAGE = 'bmdCpp', first, second, f4ColSums, f2, f3, cross, alpha, conserv)
}

#' @title
#' pvalsC
#' 
#' @description
#' The p-values in the one-sided updated step. first corresponds to the side 
#' (X or Y) the p-values will be generated for. This is side opposite to 
#' that of the index set A that is being used.
#' 
#' @param first (either X or Y) is the matrix corresponding to the first side.
#' 
#' @param second (e.g X[,A] or Y[,A]) is the sub-matrix (of the second side)
#' corresponding to the columns of the A.
#' 
#' @param f4ColSums is the rowvector columnSums(first^4)
#' 
#' @param f2 is the matrix first^2
#' 
#' @param f3 is the matrix first^3
#'
#' @param cross is the matrix cor(first, second)
#'
#' @details
#' \code{pvalsC} computes the z-statistic corresponding to the sum of 
#' correlations to the second matrix for each column of the first matrix
#' (using the variance formula from SteigerHakstian1982). 
#' The pvalue vector corresponding to the columns of first matrix is returned.
#' 
#' @export
pvalsC <- function(first, second, f4ColSums, f2, f3, cross) {
    .Call('bmdCpp_pvalsC', PACKAGE = 'bmdCpp', first, second, f4ColSums, f2, f3, cross)
}

